#ifndef SERVERDIALOG_H
#define SERVERDIALOG_H

#include <QDialog>
#include <QString>
#include <QWidget>
#if QT_VERSION >= QT_VERSION_CHECK(6, 5, 0)
#include <QtTypes>
#else
#include <QtGlobal>
#endif

namespace Ui {
class ServerDialog;
/**
 * @class ServerDialog
 * @brief Class for creating a server
 */

}

class ServerDialog : public QDialog
{
    Q_OBJECT

public:
    /**
     * @brief Constructor for ServerDialog.
     * @param parent Parent widget pointer.
     */

    explicit ServerDialog(QWidget *parent = nullptr);
    /**
     * @brief Destructor for ServerDialog.
     */

    ~ServerDialog();
    /**
     * @brief Returns the name of the server.
     * @return Server name as a QString.
     */

    QString serverName() const;
    /**
     * @brief Returns the port number entered in the dialog.
     * @return Port number as quint16.
     */

    quint16 port() const;

    /**
     * @brief Returns which player is selected to start the game.
     * @return Index representing the starting player.
     */

    quint8 whostarts() const;

private:
    /**
     * @brief Pointer to the UI generated by Qt Designer.
     */

    Ui::ServerDialog *ui;

};

#endif // SERVERDIALOG_H
